---
- name: "rebuild unified kernel images"
  command: /usr/local/bin/dracut-install-uki
  become: yes
- name: "reload systemd daemon"
  systemd:
    daemon_reload: yes
  become: yes
- name: "upgrade rEFInd on ESP"
  command: /usr/local/bin/refind-upgrade
  become: yes
