---
- hosts: all
  become: yes
  roles:
    - { role: pull, tags: ["pull"] }
    - { role: base, tags: ["base"] }
    - { role: gui, tags: ["gui"] }
    - { role: nvidia, tags: ["nvidia"] }
    - { role: latex, tags: ["latex"] }
    - role: dotfiles
      tags:
        - dotfiles
      become: yes
      become_user: "{{ user.name }}"
    - role: chinese
      tags:
        - dotfiles
        - input_method
        - chinese
      become: yes
      become_user: "{{ user.name }}"
  tasks: []
  vars_prompt:
    - name: user_password
      prompt: "Enter desired password for the new user"
