---
- hosts: all
  become: yes
  roles:
    - { role: pull, tags: ["pull"] }
    - { role: base, tags: ["base"] }
    - { role: gui, tags: ["gui"] }
    - { role: nvidia, tags: ["nvidia", "drivers"] }
    - { role: latex, tags: ["latex"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - role: chinese
      tags:
        - dotfiles
        - input_method
        - chinese
  tasks: []
  vars_prompt:
    - name: user_password
      prompt: "Enter desired password for the new user"

- hosts: laptop
  roles:
    - { role: tzupdate, tags: ["tzupdate"] }
  tasks: []

- hosts: xps9700
  roles:
    - { role: xps9700, tags: ["drivers"] }
  tasks: []
