---
- name: "Install configs"
  include_role:
    name: template-install
  vars:
    src_config_home: home/config
    dest_config_home: "~{{ user.name }}/.config"

- name: "Link .zshenv in $HOME so zsh can find it"
  file:
    src: "{{ xdg_config_home }}/zsh/.zshenv"
    dest: "~{{ user.name }}/.zshenv"
    state: link

- name: "Install ssh configs"
  block:
    - include_role:
        name: template-install
      vars:
        src_config_home: home/ssh
        dest_config_home: "~{{ user.name }}/.ssh"
    - file:
        path: "~{{ user.name }}/.ssh/masters"
        state: directory
