---
- name: "Install configs"
  include_role:
    name: template-install
  vars:
    src_config_home: home/config
    dest_config_home: "~/.config"

- name: "Link .zshenv in $HOME so zsh can find it"
  file:
    src: "{{ xdg_config_home }}/zsh/.zshenv"
    dest: "$HOME/.zshenv"
    state: link

# https://wiki.archlinux.org/index.php/XDG_MIME_Applications#mimeapps.list
- name: "Legacy support for mimeapps.list in XDG_DATA_HOME"
  file:
    src: "{{ xdg_config_home }}/mimeapps.list"
    dest: "{{ xdg_data_home }}/applications/mimeapps.list"
    state: link

- name: "Install ssh configs"
  block:
    - include_role:
        name: template-install
      vars:
        src_config_home: home/ssh
        dest_config_home: "~{{ user.name }}/.ssh"
    - file:
        path: "~{{ user.name }}/.ssh/masters"
        state: directory

- name: "Enable per-user tmpfiles service"
  systemd:
    scope: user
    name: "{{ item }}"
    enabled: yes
    state: started
    no_block: yes
  loop:
    - systemd-tmpfiles-setup.service
    - systemd-tmpfiles-clean.timer
