---
- name: "Install nvidia driver"
  pacman:
    name:
      - nvidia
      - nvidia-settings
- name: "Blacklist nouveau"
  template:
    src: etc/dracut.conf.d/blacklist-nouveau.conf.j2
    dest: etc/dracut.conf.d/blacklist-nouveau.conf
  notify:
    - rebuild unified kernel images
- name: "Enable nvidia native power management"
  template:
    src: etc/modprobe.d/nvidia-power.conf.j2
    dest: etc/modprobe.d/nvidia-power.conf
  notify:
    - rebuild unified kernel images
- name: "Nvidia power management udev rules"
  include_role:
    name: template-install
  vars:
    src_config_home: "etc/udev"
    dest_config_home: "/etc/udev"
