---
- name: "Install nvidia driver"
  pacman:
    name:
      - nvidia-dkms
      - nvidia-utils
      - nvidia-prime
- name: "Skip nouveau in initramfs"
  template:
    src: etc/dracut.conf.d/blacklist-nouveau.conf.j2
    dest: /etc/dracut.conf.d/blacklist-nouveau.conf
  notify:
    - rebuild unified kernel images
- name: "Enable nvidia native power management"
  template:
    src: etc/modprobe.d/nvidia-power.conf.j2
    dest: /etc/modprobe.d/nvidia-power.conf
  notify:
    - rebuild unified kernel images
- name: "Nvidia power management udev rules"
  copy:
    src: "etc/udev/rules.d/80-nvidia-pm.rules"
    dest: "/etc/udev/rules.d"
    mode: "0644"

# Prevent X from loading nvidia video driver by manually
# create a default screen and assign only intel GPU to it
- name: "Prevent X from loading nvidia video driver"
  copy:
    src: etc/X11/xorg.conf.d/90-static-layout.conf
    dest: /etc/X11/xorg.conf.d/
    mode: "0644"

- name: "Prevent vulkan from using nvidia"
  blockinfile:
    path: /etc/pacman.d/confs/no-nvidia-vulkan.conf
    block: |
      [options]
      NoExtract = usr/share/vulkan/icd.d/nvidia_icd.json
