---
- name: "Install fprint-tod and xps binary driver"
  include_role:
    name: aur-install
  vars:
    aur_packages:
      - libfprint-tod-git
      - libfprint-2-tod1-xps9300-bin
- name: "Mark libfprint-tod-git as deps"
  command:
    cmd: "pacman -D --asdeps libfprint-tod-git"
- name: "Install fprintd DBUS service"
  pacman:
    name: fprintd
    state: present

# TODO: howdy
