---
- name: "Install KDE plasma"
  pacman:
    name:
      - noto-fonts
      - plasma-meta
      - plasma-wayland-session
      - powerdevil
      - bluedevil
      - kde-gtk-config
      - kdeconnect
- name: "Configure SDDM"
  synchronize:
    src: etc/sddm.conf.d
    dest: /etc
- name: "Debug"
  debug:
    msg: "{{ ansible_run_tags }}"
- name: "Enable SDDM service"
  service:
    name: sddm
    enabled: yes
  when: "not with_plymouth"
- name: "Enable SDDM service (with plymouth)"
  service:
    name: sddm-plymouth
    enabled: yes
  when: "with_plymouth"
  tags:
    - plymouth
