---
- name: "Install nvm"
  include_role:
    name: aur-install
  vars:
    aur_packages: nvm
- name: "Template nvm configures"
  include_role:
    name: template-install
  vars:
    src_config_home: home/config/zsh/extra.d
    dest_config_home: "~{{ user.name }}/.config/zsh/extra.d"
