---
- name: "Enable iommu and early load vfio driver"
  template:
    src: "{{ item.src }}"
    dest: "/etc/dracut.conf.d/{{ item.path | regex_replace('\\.j2$', '') }}"
    mode: "{{ item.mode }}"
  with_filetree: ../templates/etc/dracut.conf.d/
  when: item.state == 'file'
  notify:
    - rebuild unified kernel images
