---
- name: "Install tzupdate"
  include_role:
    name: aur-install
  vars:
    aur_packages: tzupdate
- name: "Install tzupdate service"
  template:
    src: etc/systemd/system/tzupdate.service.j2
    dest: /etc/systemd/system/tzupdate.service
  notify:
    - reload systemd daemon
- name: "Enable tzupdate when network is connected"
  systemd:
    name: tzupdate.service
    enabled: yes
