---
- name: "Create user group"
  group:
    name: "{{ user.group }}"
    state: present
  tags:
    - user

# other groups are added based on different roles, e.g. rfkill for wifi and sys for CUPS
- name: "Create user and assign to group"
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password|password_hash('sha512') }}"
    shell: "{{ user.shell }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    groups:
      - uucp
      - systemd-journal
    append: yes
  tags:
    - user

- name: "Install sudo"
  pacman:
    name: sudo
    state: present
  tags:
    - sudo
- name: "Add user to wheel group"
  user:
    name: "{{ user.name }}"
    groups: wheel
    append: yes
  tags:
    - sudo
    - user
- name: "Update sudo configurations"
  template:
    src: "etc/sudoers.d/{{ item }}.j2"
    dest: "/etc/sudoers.d/{{ item }}"
    validate: 'visudo -cf %s'
  loop:
    - 00-basic
    - 00-gui
  tags:
    - sudo

- import_tasks: packaging.yml
- import_tasks: fonts.yml
- import_tasks: booting.yml
- import_tasks: network.yml
