---
- name: "Setup AUR helper user"
  user:
    name: aur_builder
    group: wheel
- name: "Make sure aur_builder can run pacman with passwordless sudo"
  lineinfile:
    path: /etc/sudoers.d/50-aur_builder-pacman
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
- name: "Install AUR helper"
  include_role:
    name: aur-install
  vars:
    aur_packages: yay
- name: "Install basic packages"
  include_role:
    name: aur-install
  vars:
    aur_packages: "{{ basic_packages }}"
- name: "Enable pacman to also look for packages in user home"
  lineinfile:
    path: /etc/pacman.conf
    backrefs: yes
    regexp: '^CacheDir(\s+=)((?:(?:\s+\S+(?!\S))(?<!\s/home/{{ user.name }}/.cache/packages))+\s*?)(\n?)$'
    insertafter: "^#CacheDir"
    line: 'CacheDir\1\2 /home/{{ user.name }}/.cache/packages\3'
    state: present
- name: "Enable fancier output for pacman"
  lineinfile:
    path: /etc/pacman.conf
    backrefs: yes
    regexp: "^{{ item }}"
    insertafter: "^#{{ item }}"
    line: "{{ item }}"
    state: present
  loop:
    - "Color"
    - "TotalDownload"
    - "VerbosePkgLists"

- name: "Enable parallel build for makepkg"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "^MAKEFLAGS"
    insertafter: "^#MAKEFLAGS"
    line: 'MAKEFLAGS="-j"'
    state: present
- name: "Use in memory build dir for makepkg"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "^BUILDDIR"
    insertafter: "^#BUILDDIR"
    line: 'BUILDDIR=/tmp/makepkg'
    state: present
- name: "Set packager for makepkg"
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "^PACKAGER"
    insertafter: "^#PACKAGER"
    line: 'PACKAGER="Aetf <aetf@unlimited-code.works>"'
    state: present
