---
- name: "Setup AUR helper user"
  user:
    name: aur_builder
    group: wheel
- name: "Make sure aur_builder can run pacman with passwordless sudo"
  lineinfile:
    path: /etc/sudoers.d/50-aur_builder-pacman
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
- name: "Install AUR helper"
  aur:
    name: yay
    state: present
  become: yes
  become_user: aur_builder
- name: "Install basic packages"
  aur:
    name: "{{ basic_packages }}"
    state: present
  become: yes
  become_user: aur_builder
- name: "Enable pacman to also look for packages in user home"
  lineinfile:
    path: /etc/pacman.conf
    backrefs: yes
    regexp: "^#CacheDir(.+)$"
    line: "CacheDir\\1 /home/{{ user.name }}/.cache/packages"
    state: present
- name: "Enable fancier output for pacman"
  lineinfile:
    path: /etc/pacman.conf
    backrefs: yes
    regexp: "^#{{ item }}"
    line: "{{ item }}"
    state: present
  loop:
    - "Color"
    - "TotalDownload"
    - "VerbosePkgLists"
